Output docs/demo.gif
Set FontSize 16
Set Width 1000
Set Height 520
Set Theme { "name": "Molokai", "background": "#121212", "foreground": "#bbbbbb", "cursor": "#bbbbbb", "black": "#121212", "red": "#fa2573", "green": "#98e123", "yellow": "#dfd460", "blue": "#1080d0", "magenta": "#c33ff3", "cyan": "#44dfd8", "white": "#bbbbbb", "brightBlack": "#555555", "brightRed": "#fa2573", "brightGreen": "#98e123", "brightYellow": "#dfd460", "brightBlue": "#1080d0", "brightMagenta": "#c33ff3", "brightCyan": "#44dfd8", "brightWhite": "#ffffff" }
Type "env -u DEMO_LIVE node scripts/demo.mjs"
Enter
Sleep 1s
